# Generated by Django 4.1.6 on 2023-02-06 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_stream_createdon_alter_classes_stream_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='stream',
        ),
        migrations.AddField(
            model_name='profile',
            name='classes',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='insta.classes'),
            preserve_default=False,
        ),
    ]
