# Generated by Django 4.1.6 on 2023-02-06 16:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0004_remove_profile_stream_profile_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='createdOn',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
