# Generated by Django 4.1.6 on 2023-02-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0005_classes_createdon'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('student', 'Student')], default='student', max_length=10),
            preserve_default=False,
        ),
    ]
