# Generated by Django 4.1.6 on 2023-02-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0006_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='regNumber',
            field=models.CharField(default='fdcgvxhbsj', max_length=20),
            preserve_default=False,
        ),
    ]
