# Generated by Django 4.1.6 on 2023-02-06 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insta', '0007_profile_regnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='createdOn',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classes',
            name='classTeacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='class+', to=settings.AUTH_USER_MODEL),
        ),
    ]
